(()=>{'use strict';
const DATA=JSON.parse(document.getElementById('library-data').textContent),R=DATA.records,T=DATA.taxonomy,P=Object.fromEntries(T.procedures.map(p=>[p.id,p])),S=Object.fromEntries(T.sections.map(s=>[s.id,s]));
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)&&!x.username&&!x.password?x.href:''}catch{return ''}};
const link=(u,label,cls='')=>safe(u)?`<a href="${esc(safe(u))}" target="_blank" rel="noopener noreferrer" class="${esc(cls)}">${esc(label)} ↗</a>`:'';
const scopeName={fulltext:'正文阅读笔记',abstract:'摘要阅读笔记',metadata:'题录资料',restricted:'来源受限',official_page:'官方页面阅读笔记',partial:'部分正文阅读笔记'};
const completionName={substantive:'已有详细笔记',limited:'笔记待补充',pending:'待完成详细阅读'};
const stateName={verified:'已核对身份',matched:'已核对身份',pending:'身份待核实',conflict:'身份有冲突',restricted:'核验受限',unknown:'未核实',tested:'已测试',playing:'已播放测试',failed:'测试失败'};
let st={},shown=40,selected=null;const defaults={view:'library',q:'',section:'',procedure:'',kind:'',year:'',type:'',language:'',source:'',fulltext:'',access:'',verification:'',video_type:'',completion:'',sort:'seed',id:''};
function hashState(){const p=new URLSearchParams(location.hash.slice(1));st={...defaults,...Object.fromEntries(p)};if(location.hash&&!location.hash.includes('=')){const a=decodeURIComponent(location.hash.slice(1)),matches=R.filter(r=>r.id===a||r.aliases.some(x=>x.id===a||x.edition+':'+x.id===a));if(matches.length)st.id=matches[0].id;if(matches.length>1)toast('此旧编号在两版文档中对应不同资源，已默认打开扩充版；旧版可用 original:编号 定位。');}if(!['library','coverage','updates'].includes(st.view))st.view='library';}
function save(push=false){const p=new URLSearchParams(Object.entries(st).filter(([k,v])=>v&&v!==defaults[k]));history[push?'pushState':'replaceState'](null,'','#'+p);}
function tag(t,cls=''){return `<span class="tag ${cls}">${esc(t)}</span>`}
function noteScope(r){return r.note?.scope||'pending'}
function completion(r){if(!r.note||['metadata','restricted'].includes(r.note.scope))return 'pending';return r.note.completion==='substantive'?'substantive':'limited'}
function bag(r){return [r.title,r.note?.zh_title,r.note?.question,r.note?.design,r.note?.methods,...(r.note?.results||[]),r.note?.interpretation,...(r.note?.limitations||[]),...(r.note?.evidence_issues||[]),...(r.note?.evidence_review?.issues||[]).map(x=>x.original+' '+x.finding),r.note?.scope_description,r.seed_description,...r.authors,r.doi,r.pmid,r.pmcid,...r.aliases.map(x=>x.id),...r.procedures.map(x=>P[x]?P[x].zh+' '+P[x].en:'')].join(' ').toLowerCase();}
const bags=new Map(R.map(r=>[r.id,bag(r)]));
const concerns=r=>r.kind==='literature'&&Boolean(r.note?.evidence_issues?.length);
const unread=r=>r.kind==='literature'&&completion(r)!=='substantive';
function matches(r,ignoreKind=false){if(!ignoreKind&&st.kind==='unread'&&!unread(r))return false;if(!ignoreKind&&st.kind==='concerns'&&!concerns(r))return false;if(st.section&&r.section!==st.section&&!r.cross_sections.includes(st.section))return false;if(st.procedure&&!r.procedures.includes(st.procedure))return false;if(st.kind&&!['unread','concerns'].includes(st.kind)&&!ignoreKind&&r.kind!==st.kind)return false;
if(st.q&&!st.q.toLowerCase().trim().split(/[\s/／]+/).every(q=>bags.get(r.id).includes(q)))return false;
for(const k of ['year','resource_type','language','source']){const sk=k==='resource_type'?'type':k;if(st[sk]&&String(r[k]??'')!==st[sk])return false;}
if(st.completion&&(r.kind!=='literature'||completion(r)!==st.completion))return false;if(st.fulltext&&noteScope(r)!==st.fulltext)return false;if(st.access&&(r.kind!=='literature'||r.fulltext.status!==st.access))return false;if(st.verification&&r.identity.status!==st.verification)return false;if(st.video_type&&(r.kind!=='video'||r.resource_type!==st.video_type))return false;return true;}
function options(key,items,label){return `<label>${label}<select data-filter="${key}" aria-label="${label}"><option value="">全部</option>${items.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('')}</select></label>`}
function controls(){const unique=k=>[...new Set(R.map(r=>r[k]).filter(Boolean))].sort().map(x=>[x,x]);$('#filters').innerHTML=options('year',unique('year').reverse(),'发表 / 页面年份')+options('type',unique('resource_type'),'资料类型')+options('language',[['zh','中文资料'],['en','英文资料']],'资料语言')+options('source',unique('source'),'来源')+options('completion',Object.entries(completionName),'笔记完成情况')+options('fulltext',Object.entries(scopeName),'阅读深度')+options('access',[['retrieved','正文已取得（范围见笔记）'],['matched','已匹配入口，未取得正文'],['unknown','暂无已核实全文入口']],'全文取得状态')+options('verification',[...new Set(R.map(r=>r.identity.status))].map(x=>[x,stateName[x]||x]),'身份核验')+options('video_type',[...new Set(R.filter(r=>r.kind==='video').map(r=>r.resource_type))].map(x=>[x,x]),'视频类型');
$('#filters').addEventListener('change',e=>{st[e.target.dataset.filter]=e.target.value;st.id='';shown=40;render()});}
function tree(){let html='';for(const sec of T.sections){const ps=T.procedures.filter(p=>p.section===sec.id);let sub='';html+=`<details ${st.section===sec.id||st.procedure&&P[st.procedure]?.section===sec.id?'open':''}><summary>${esc(sec.zh)} <small>${R.filter(r=>r.section===sec.id).length}</small></summary><button class="procedure ${st.section===sec.id&&!st.procedure?'active':''}" data-sec="${sec.id}">查看本板块</button>`;for(const p of ps){if(p.subspecialty!==sub){sub=p.subspecialty;html+=`<div class="subheading">${esc(sub)}</div>`;}html+=`<button class="procedure ${st.procedure===p.id?'active':''}" data-proc="${p.id}">${esc(p.zh)} <span>${R.filter(r=>r.procedures.includes(p.id)).length}</span></button>`}html+='</details>'}$('#tree').innerHTML=html;}
function card(r){const n=r.note,zh=n?.zh_title||r.seed_description?.split('。')[0]||r.title;return `<div class="card ${selected?.id===r.id?'selected':''}" data-card="${r.id}"><div class="kind-label">${r.kind==='video'?'▶ 视频资源':'文献 / 专业资料'} · ${esc(r.aliases[0]?.id||r.id)}</div><h3><button data-read="${r.id}">${esc(zh)}</button></h3><p class="original">${esc(r.title)}</p><div class="meta">${esc(r.year||'年份未核实')} · ${esc(r.source)}</div>${r.kind==='literature'?tag(scopeName[n?.scope]||'待完成阅读',completion(r)==='substantive'?'good':'warn')+tag(completionName[completion(r)],completion(r)==='substantive'?'good':'warn'):tag(r.video.playback==='playing'?'播放已测试':'播放未确认','warn')}${concerns(r)?tag('原文存在疑点','warn'):''}${tag(stateName[r.identity.status]||r.identity.status,r.identity.status==='verified'?'good':'muted')}</div>`}
function section(title,value){if(!value||Array.isArray(value)&&!value.length)return '';return `<section class="note-section"><h3>${title}</h3>${Array.isArray(value)?'<ul>'+value.map(t=>'<li>'+esc(typeof t==='string'?t:JSON.stringify(t))+'</li>').join('')+'</ul>':'<p>'+esc(typeof value==='string'?value:JSON.stringify(value))+'</p>'}</section>`}
function reviewHistory(n){const review=n?.evidence_review;if(!review?.issues?.length)return '';const labels={resolved:'已厘清',retained:'仍需澄清',reclassified:'转为研究局限'},counts=review.issues.reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{});return `<section class="note-section"><h3>本轮疑点复核</h3><p>${esc(new Date(review.checked_at).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'}))} · ${Object.entries(labels).filter(([k])=>counts[k]).map(([k,v])=>v+' '+counts[k]+' 项').join(' · ')}。已厘清表示本笔记中的阅读口径有了依据，不代表期刊已发布勘误。</p><details class="evidence"><summary>展开逐项结论与来源</summary><ol class="sources">${review.issues.map(x=>`<li><strong>${esc(labels[x.status]||x.status)}</strong><p>原问题：${esc(x.original)}</p><p>${esc(x.finding)}</p>${(x.sources||[]).map(y=>link(y.url,y.locator||'复核来源')).join('<br>')}</li>`).join('')}</ol></details></section>`;}
function showReading(r){if(!r){$('#reading').innerHTML='<div class="empty">选择一篇文献，阅读详细笔记；或打开具体视频的原站页面。</div>';return;}
const n=r.note,title=n?.zh_title||r.seed_description?.split('。')[0]||r.title;
let html=`<div class="kind-label">${r.kind==='video'?'SURGICAL VIDEO':'READING NOTES'} · ${esc(r.aliases[0]?.id||r.id)}</div><h2>${esc(title)}</h2><p class="original-title" lang="en">${esc(r.title)}</p><p class="byline">${esc(r.authors.slice(0,8).join(' · '))}${r.authors.length>8?' 等':''}<br>${esc(r.year||'年份未核实')} · ${esc(r.source)} · ${esc(r.resource_type)}</p><div>${r.procedures.map(x=>P[x]?tag(P[x].zh):'').join('')}</div>`;
if(r.corrections?.length)html+=section('原始题录关联通知',r.corrections.map(x=>x.type+' · PMID '+(x.pmid||'未给出')+'；请按通知类型阅读，不统一视为撤稿。'));if(r.source_changed_since_note)html+='<div class="read-scope">来源页面曾检测到内容变化；阅读时请以笔记标明的来源、版本与核对时间为准。</div>';if(r.kind==='video'){
html+=`<div class="video-stage"><span class="play">▷</span><div><strong>前往原站观看</strong><p>原站视频卡片 · 不下载或重新托管</p></div></div><div class="source-buttons">${link(r.urls[0]?.url,'前往原站观看','primary')}</div>`;
html+=section('内容概括',r.video.summary)+section('概括依据',r.video.summary_basis)+section('观看信息',[`页面核验：${r.page_checks[0]?.page_state||'待核对'}`,`播放测试：${stateName[r.video.playback]||r.video.playback}；${r.video.playback_evidence||'尚无实际播放证据'}`,`时长：${r.video.duration||'未核实'}；配音：${r.video.audio_language||'未核实'}；字幕：${r.video.subtitle_language||'未核实'}`,`嵌入条件：${r.video.embedding==='unknown'?'尚未确认，使用原站链接':r.video.embedding}；嵌入测试：${r.video.embed_test==='not_attempted'?'未进行':r.video.embed_test}`]);
if(r.video.relations?.length)html+=section('文献关联',r.video.relations.map(x=>(x.type==='supplement'?'原文明确的配套视频：':'同主题独立教学：')+x.title+'。依据：'+x.evidence));
}else{
const s=n?.scope,validFull=Boolean(r.fulltext.url)&&(r.fulltext.status==='matched'||r.fulltext.status==='retrieved');
html+=`<div class="source-buttons">${link(r.urls[0]?.url,'文章页面')}${r.pmid?link('https://pubmed.ncbi.nlm.nih.gov/'+r.pmid+'/','PubMed'):''}${r.doi?link('https://doi.org/'+r.doi,'DOI'):''}${validFull?link(r.fulltext.url,'已匹配全文入口','primary'):''}</div>`;
html+=`<div class="read-scope"><strong>${scopeName[s]||'尚待完成实质阅读'} · ${completionName[completion(r)]}</strong><br>${s==='abstract'?'以下笔记依据已读取摘要；全文中的方法、结果表、亚组和补充材料尚未核读。':s==='fulltext'?'已读取可取得正文；具体核对范围见各节和来源定位。':n?.scope_description||'本条保留来源与核验记录。尚未取得足以形成完整阅读笔记的正文。'}${!validFull?'<br>暂无已核实全文入口。':''}</div>`;
if(n){if(n.scope_description&&['abstract','fulltext'].includes(s))html+=section('实际阅读范围',n.scope_description);if(concerns(r))html+=`<aside class="source-concerns" aria-label="原文疑点"><strong>原文疑点 · 请结合核对说明阅读</strong><p>这里记录原文的数字、方法或报告问题。笔记是否完成，按实际阅读和内容是否充分另行判断。</p>${section('已核对的问题与使用边界',n.evidence_issues)}</aside>`;html+=reviewHistory(n)+section('这篇资料回答什么问题',n.question)+section('研究设计与对象 / 资料范围',n.design)+section('方法与具体内容',n.methods)+section('关键结果与证据',n.results)+section('如何理解这项证据',n.interpretation)+section('局限与阅读注意',n.limitations);if(n.sources?.length)html+=`<section class="note-section"><h3>笔记依据与定位</h3><ol class="sources">${n.sources.map(x=>`<li>${link(x.url,x.locator||x.title||'来源页面')}${x.locator?'<br>'+esc(x.locator):''}</li>`).join('')}</ol></section>`;}else html+=section('目前取得的信息',r.seed_description)+section('待补充内容','原文或摘要仍在核验中；该条目不计为已完成详细笔记。');
}
html+=`<details class="evidence"><summary>查看资源身份、原编号与逐次核验依据</summary><p>身份：${esc(stateName[r.identity.status]||r.identity.status)} · ${esc(r.identity.checked_at||'尚无本轮核验时间')}</p>${r.identity.conflicts?.length?'<p>'+esc(r.identity.conflicts.join('；'))+'</p>':''}<p>DOI ${esc(r.doi||'—')} · PMID ${esc(r.pmid||'—')} · PMCID ${esc(r.pmcid||'—')}</p><p>${r.aliases.map(a=>esc((a.edition==='expanded'?'扩充版':'旧版')+' '+a.id)).join(' · ')}</p><ul>${r.page_checks.map(c=>'<li>'+link(c.requested_url,'来源页面')+'：'+esc(c.page_state||c.state||'未完成')+'；HTTP '+esc(c.status??'未知')+'；'+esc(c.checked_at||'')+(c.page_title?'<br>'+esc(c.page_title):'')+'</li>').join('')}</ul>${r.identity.related_publications?.length?section('已核对的更正关联',r.identity.related_publications.map(x=>x.relation+'：'+x.scope+'；PMID '+x.pmid)):''}</details><div class="reading-tools"><span>笔记核对：${esc(n?.reviewed_at?.slice(0,10)||'待完成')}</span><button id="copy-item">复制本条链接</button></div>`;
$('#reading').innerHTML=html;$('#copy-item').onclick=()=>copy(location.href);}
async function copy(value){try{await navigator.clipboard.writeText(value);toast('链接已复制')}catch{toast('请复制浏览器地址栏中的链接')}}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,3000)}
function coverage(){const rows=DATA.coverage||[];$('#coverage').innerHTML=`<p class="eyebrow">SCOPE & GAPS</p><h1>收录范围与缺口</h1><p>这是一份按术式维护的资源库。格内数量来自当前去重记录，包含待核实资源；“尚未检索”表示尚无该维度的完整检索记录，不等于没有文献。不能将术式覆盖等同于全部文献召回率。</p><div class="audit-card"><h2>七个板块，开放的术式目录</h2><p>经典研究、付费文献题录、技术资料、长期随访和官方教学视频均可收录。中文为跨板块聚合入口。全文与摘要分层展示，独立教学视频不冒充论文配套材料。</p><div class="table-wrap"><table><thead><tr><th>术式 / 专题</th><th>指南</th><th>比较 / 随访</th><th>技术资料</th><th>视频</th><th>并发症</th><th>中文 / 英文</th></tr></thead><tbody>${rows.map(x=>'<tr><td><button data-proc="'+esc(x.id)+'">'+esc(P[x.id]?.zh||x.id)+'</button></td>'+['guideline','comparative','technical','video','complication'].map(k=>'<td>'+esc(x[k]?.count?x[k].count+' 条':x[k]?.status||'尚未检索')+'</td>').join('')+'<td>'+x.zh+' / '+x.en+'</td></tr>').join('')}</tbody></table></div></div><div class="audit-card"><h2>优先补漏方向</h2><ul class="audit-list"><li>复杂 PVR、巨大裂孔、内界膜变式、儿童视网膜手术。</li><li>PRESERFLO、SLT/LPI 与睫状体治疗的来源及技术细分。</li><li>角膜环、穿孔修补、交联；复杂眼眶、泪道与斜视。</li><li>眼肿瘤敷贴与动脉化疗；中文视频详情页与实际播放。</li></ul><p>逐条对账及运行证据随项目维护文件保存。${esc(DATA.audit_summary||'')}</p></div>`;}
function updates(){const s=DATA.status||{};$('#updates').innerHTML=`<p class="eyebrow">UPDATE LOG</p><h1>真实更新状态</h1><div class="audit-card"><h2>${esc(s.deployed?'远程部署记录':'本地构建 · 远程状态尚未证实')}</h2><p>调度：${esc(s.schedule_description||'每周一 09:17，Asia/Shanghai；GitHub Actions 01:17 UTC。配置生成不等于已启用。')}</p><ul class="audit-list">${[['最近尝试',s.last_attempt],['全流程最近成功',s.last_success],['最近部署',s.last_deploy],['本次云端执行范围',s.remote_runtime?.run_scope==='publish-reviewed'?'发布已经核验的资料与页面修订，未重复检索':'来源更新与发布'],['下次计划',s.next_run],['实际定时触发',s.observed_scheduled_run||'尚未发生；当前为人工触发的云端验收运行'],['远程调度状态',s.schedule_state||'未部署或尚未验证']].map(([a,b])=>'<li>'+a+'：'+esc(b||'尚无记录')+'</li>').join('')}</ul><p>手动触发成功与未来定时触发分别记录；超过 10 天没有成功更新时显示逾期提示。</p></div><div class="audit-card"><h2>各来源运行记录</h2><div class="table-wrap"><table><thead><tr><th>来源</th><th>本次状态</th><th>命中 / 新增</th><th>最近成功</th></tr></thead><tbody>${Object.entries(s.sources||{}).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+esc(v.status)+'</td><td>'+esc(v.hits??'—')+' / '+esc(v.added??'—')+'</td><td>'+esc(v.last_success||'尚无')+'</td></tr>').join('')}</tbody></table></div></div><div class="audit-card"><h2>失败后的恢复</h2><p>抓取失败保留上一次数据，不以空结果覆盖。身份或内容存在冲突的候选进入待复核队列；通过核验的题录可以独立发布。恢复使用仓库上一成功版本，再手动重跑工作流。正文笔记不会被自动更新覆盖。</p><p>本次构建版本：${esc(DATA.version)}<br>构建时间：${esc(DATA.built_at)}。构建时间不代表所有来源已经重新核验。</p>${s.workflow_url?link(s.workflow_url,'打开远程工作流'):''}</div>`;}
function render(push=false){save(push);for(const v of ['library','coverage','updates'])$('#'+v).hidden=st.view!==v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===st.view));if(st.view==='coverage'){coverage();return}if(st.view==='updates'){updates();return}
$('#query').value=st.q;$('#sort').value=st.sort;document.querySelectorAll('[data-filter]').forEach(x=>x.value=st[x.dataset.filter]);document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===st.kind));tree();$('#breadcrumb').textContent=['全部资源',st.section&&S[st.section]?.zh,st.procedure&&P[st.procedure]?.zh,st.language==='zh'&&'中文资源'].filter(Boolean).join(' / ');
$('#article-count').textContent=R.filter(r=>r.kind==='literature'&&matches(r,true)).length;$('#unread-count').textContent=R.filter(r=>unread(r)&&matches(r,true)).length;$('#concerns-count').textContent=R.filter(r=>concerns(r)&&matches(r,true)).length;$('#video-count').textContent=R.filter(r=>r.kind==='video'&&matches(r,true)).length;
let filtered=R.filter(r=>matches(r));if(st.sort!=='seed')filtered.sort((a,b)=>(st.sort==='newest'?-1:1)*((a.year||0)-(b.year||0)));
selected=filtered.find(r=>r.id===st.id)||filtered[0]||null;if(selected&&st.id!==selected.id){st.id=selected.id;save()}else if(!selected&&st.id){st.id='';save()}
$('#result-count').textContent=filtered.length+(st.kind==='unread'?' 条资料 · 笔记内容仍待补充':st.kind==='concerns'?' 条资料 · 原文问题及核对说明':' 条资源');$('#cards').innerHTML=filtered.slice(0,shown).map(card).join('')||'<p class="empty">暂无匹配资源。可以清除部分筛选条件。</p>';$('#more').hidden=filtered.length<=shown;$('#filter-summary').textContent=Object.keys(defaults).filter(k=>!['view','id','sort'].includes(k)&&st[k]).length?'（已有筛选条件）':'';showReading(selected);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.read){st.id=b.dataset.read;render(true);if(innerWidth<851)$('#reading').scrollIntoView({behavior:'smooth'});}if(b.dataset.proc||b.dataset.sec){st.procedure=b.dataset.proc||'';st.section=b.dataset.sec||P[b.dataset.proc].section;st.id='';st.view='library';shown=40;$('#catalog').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');render(true);}if(b.dataset.view){st.view=b.dataset.view;render(true)}if(b.hasAttribute('data-kind')){st.kind=b.dataset.kind;st.id='';shown=40;render()}});
$('#query').addEventListener('input',e=>{st.q=e.target.value;st.id='';shown=40;render()});$('#clear').onclick=()=>{st={...defaults};shown=40;render()};$('#all').onclick=()=>{st.section='';st.procedure='';st.id='';st.view='library';render()};$('#chinese').onclick=()=>{st.language='zh';st.section='';st.procedure='';st.id='';st.view='library';render()};$('#sort').onchange=e=>{st.sort=e.target.value;render()};$('#more').onclick=()=>{shown+=40;render()};$('#close-menu').onclick=()=>{$('#catalog').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')};$('#menu').onclick=()=>{const open=$('#catalog').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open))};$('#copy-context').onclick=()=>copy(location.href);$('#top').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#catalog').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}});window.onpopstate=()=>{hashState();render()};
const s=DATA.status||{},overdueBase=s.last_success||s.first_attempt,overdue=overdueBase&&Date.now()-Date.parse(overdueBase)>10*86400000;$('#statusbar').textContent=(s.deployed?'已部署':'本地阅读版')+' · '+(s.schedule_state||'远程周更尚未验证')+(overdue?' · 更新已逾期，请查看运行记录':'')+' · 视频播放与页面核验分别记录';
$('#stats').textContent=`${R.filter(r=>r.kind==='literature').length} 篇文献与资料 · ${R.filter(r=>r.kind==='video').length} 条视频 · ${R.filter(r=>r.kind==='literature'&&completion(r)==='substantive').length} 篇已有详细笔记 · ${R.filter(unread).length} 篇笔记待补 · ${R.filter(concerns).length} 篇标注原文疑点（阅读深度分别标明）`;controls();hashState();render();
if(location.protocol==='https:'&&DATA.deployment?.status_url){Promise.allSettled([fetch(DATA.deployment.status_url,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('receipt');return r.json()}),fetch(DATA.deployment.runtime_status_url,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('runtime');return r.json()})]).then(([a,b])=>{const receipt=a.status==='fulfilled'?a.value:null,runtime=b.status==='fulfilled'?b.value:null;if(receipt?.deployed&&receipt.data_version===DATA.version){DATA.status={...DATA.status,deployed:true,last_deploy:receipt.verified_at,next_run:receipt.next_planned_run,observed_scheduled_run:receipt.observed_scheduled_run,workflow_url:receipt.run_url,schedule_state:receipt.schedule_active===true?'远程周更已启用；未来定时触发另行记录':'云端部署已核验；定时状态见运行记录'};}if(runtime){if(runtime.run_scope!=='publish-reviewed')DATA.status.last_attempt=runtime.started_at;DATA.status.remote_runtime=runtime;DATA.status.last_success=runtime.last_success||DATA.status.last_success;DATA.status.first_attempt=runtime.first_started_at||DATA.status.first_attempt;DATA.status.observed_scheduled_run=runtime.observed_scheduled_run||DATA.status.observed_scheduled_run;}$('#statusbar').textContent='在线阅读版 · '+(DATA.status.deployed?'部署字节已核验':'部署回执待核验')+' · '+(runtime?.status==='partial'?'部分来源更新受限':runtime?.status==='failed'?'最近更新失败，保留已发布版本':DATA.status.schedule_state||'查看更新记录');const overdueAt=DATA.status.last_success||DATA.status.first_attempt;if(overdueAt&&Date.now()-Date.parse(overdueAt)>10*86400000)$('#statusbar').textContent+=' · 全流程成功更新已逾期，请查看运行记录';if(st.view==='updates')updates();}).catch(()=>{});}
})();
